//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAM0230_Project_group_1.domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KolledzDBEntities : DbContext
    {
        public KolledzDBEntities()
            : base("name=KolledzDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<groups> groups { get; set; }
        public virtual DbSet<oppevorms> oppevorms { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<students> students { get; set; }
        public virtual DbSet<subject_group> subject_group { get; set; }
        public virtual DbSet<subject_student> subject_student { get; set; }
        public virtual DbSet<subject_teacher> subject_teacher { get; set; }
        public virtual DbSet<subjects> subjects { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<visits> visits { get; set; }
    }
}
