//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAM0230_Project_group_1.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subject()
        {
            this.subject_group = new HashSet<subject_group>();
            this.subject_student = new HashSet<subject_student>();
            this.subject_teacher = new HashSet<subject_teacher>();
        }
    
        public int ID { get; set; }
        public string lekt { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string semester { get; set; }
        public Nullable<decimal> lecture_hours { get; set; }
        public Nullable<decimal> practice_hours { get; set; }
        public Nullable<decimal> exercises_hours { get; set; }
        public int oppevorm_id { get; set; }
        public string language { get; set; }
    
        public virtual oppevorm oppevorm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subject_group> subject_group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subject_student> subject_student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subject_teacher> subject_teacher { get; set; }
    }
}
