//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAM0230_Project_group_1.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject_group
    {
        public int ID { get; set; }
        public string subject_code { get; set; }
        public int group_id { get; set; }
    
        public virtual groups groups { get; set; }
        public virtual subjects subjects { get; set; }
    }
}
