//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit
    {
        public int ID { get; set; }
        public string student_code { get; set; }
        public System.DateTime date { get; set; }
        public string lesson_type { get; set; }
        public Nullable<int> paar_nr { get; set; }
        public Nullable<int> subject_id { get; set; }
    
        public virtual student student { get; set; }
        public virtual subject subject { get; set; }
    }
}
